### ISSUE TITLE
Lolin V3 freeze 

### ISSUE THREAD

**Issue by Obsthaendler** [Eisbaeeer/Ferraris_MQTT_Energy_Counter_Meter_TCRT5000#1]
Ab und zu friert der esp ein. Dann muss ich immer ein reset machen. Könnte es sein das der eprom Speicher voll läuft?
Nutze einen NodeMCU Lolin V3 Module ESP8266 ESP-12F WIFI

**Comment by Eisbaeeer** [comment]
Bisher habe ich keine Probleme feststellen können. Die Counter laufen ohne Watchdog. Und ich bekomme ständig die aktuellen Daten. Bisher konnte ich keine Differenz zu den mechanischem Zähler feststellen. Compiliert wurde mit NodeMCU v.1.0 obwohl auch hier schon die V.3 im Einsatz ist.

**Comment by Obsthaendler** [comment]
Danke für die Antwort. Dann muss ich mal auf die Suche gehen, eben hatte ich sogar nach einem Stromreset wieder ein freeze. 

EDIT: Scheinbar lag die Ursache an der falschen bzw. extremen Abtastrate, die den Freeze verursacht hat. 
EDIT2: Doch nicht, wieder ein Freeze.
