### ISSUE TITLE
meter counter overflow

### ISSUE THREAD

**Issue by Gelbwichtel** [Eisbaeeer/Ferraris_MQTT_Energy_Counter_Meter_TCRT5000#13]
Hi, tolles Projekt, schade dass ich erst jetzt darauf gestoßen bin.
Ich hab gerade festgestellt, dass ich mit den kWh von meinem Zähler nicht arbeiten kann, denn dies führt zum Zahlenüberlauf.
Ich muss von **2218269** die beiden ersten Stellen weglassen, damit der Wert noch in einen **int32_t** passt.

Hi, great project, too bad I only came across it now.
I just realized that I can't work with the kWh from my meter, because this leads to number overflow.
I have to leave out the first two digits from **2218269** so that the value still fits into an **int32_t**.

cu
Gelbwichtel

**Comment by Eisbaeeer** [comment]
Hi
Du kannst die Variable in der configuration.json einfach größer wählen.
![image](https://user-images.githubusercontent.com/4928271/204154392-1718c605-6fec-40c3-b53d-c9a3469a9835.png)
Neu compilieren und dein Zählerstand sollte reinpassen.

**Comment by Gelbwichtel** [comment]
funktioniert. Danke
