### ISSUE TITLE
NodeMCU disconnect after some time

### ISSUE THREAD

**Issue by Bytechanger** [Eisbaeeer/Ferraris_MQTT_Energy_Counter_Meter_TCRT5000#14]
For some reason the NodeMCU stop working.
After a while (days) it stops sending data over MQTT and isn´t connected to wlan.
An other device (NodeMCU other firmware at same position) is working well for months.

**Comment by Eisbaeeer** [comment]
Hello Bytechanger
This issue is not software related. Please check your MCU or antenna.
