### ISSUE TITLE
Increase digits of username and password

### ISSUE THREAD

**Issue by bernemer** [Eisbaeeer/Ferraris_MQTT_Energy_Counter_Meter_TCRT5000#15]
Hi Eisbaeer,

i found your ferraris counter am I'm thrilled.
Gerate job.
I have one more request.
Is it possible to increase the number of digits in the password and the username to 24 digits?
I would like to send the data to thingspeak because i can only access the internet via my neighbor's wifi there.
The thinkspeak mqtt access generate usernames and passwords with 24 digits.

Thanks

Grüße aus Frankfurt/Main

Marcus

**Comment by Eisbaeeer** [comment]
Solved with version 0.93

**Comment by bernemer** [comment]
Thank you
