### ISSUE TITLE
0.93 under Dashbord: There are no items defined in the JSON file

### ISSUE THREAD

**Issue by bernemer** [Eisbaeeer/Ferraris_MQTT_Energy_Counter_Meter_TCRT5000#16]
Hi Eisbaeeer, 
under dashbord i get the message : There are no items defined in the JSON file
There is no configuration. 

Is there somthing missing in the bin or did i make a mistake?

**Comment by Eisbaeeer** [comment]
Are you able to compile the project by yourself with platformio? I think the react enviroment is missing. In this case there is no web-part compiled.

**Comment by bernemer** [comment]
At the moment i work with the Ardurino IDE. 
Then i will install platformio in in the holidys and test it.

**Comment by bernemer** [comment]
I close the issue at first. I think i can test it in 3 weeks.

**Comment by mariusgrams** [comment]
Same here, not fixed yet
