### ISSUE TITLE
Deaktivierung von unnötigen Zählern

### ISSUE THREAD

**Issue by interceptor70** [Eisbaeeer/Ferraris_MQTT_Energy_Counter_Meter_TCRT5000#17]
Hallo ich habe mal eine frage ich habe nur einen Zähler und bekomme immer alle angezeigt

gibt es eine Möglichkeit die unnötigen zu deaktivieren ?

LG Gerrit

**Comment by Eisbaeeer** [comment]
Es werden immer alle 4 Zähler angezeigt. Spielt aber keine Rolle, da die unbenutzen das System nicht belasten.
