### ISSUE TITLE
Use better MQTT format and announce the device

### ISSUE THREAD

**Issue by rmeissn** [Eisbaeeer/Ferraris_MQTT_Energy_Counter_Meter_TCRT5000#2]
I'm using mosquitto as a MQTT broker and homeAssistant (HA) for home automation. HA wasn't able to auto discover the energy meter, as it won't announce itself over MQTT and is not using json to report itself as a device (or 4 devices). I had to fiddle with config files and parsing of announces values to get correct entities into HA.
It would be really helpful to announce your device over MQTT and use json to transmit the recorded values. You can find examples at: https://www.home-assistant.io/docs/mqtt/discovery/

**Comment by Eisbaeeer** [comment]
Added with last pull-request.
