### ISSUE TITLE
Huge spikes in the measured kW

### ISSUE THREAD

**Issue by m-kloeckner** [Eisbaeeer/Ferraris_MQTT_Energy_Counter_Meter_TCRT5000#6]
Thank you for this project! I tried to achieve the same with ESPHome, but failed to calibrate the sensor. The dashboard with the analog sensor really helps with that.

However, I am still facing issues with bouncing. Sometimes one round results in a spike of the measured kW. See screenshot from my sensor in Home-Assistant.

I already tried adjusting the poti and the debouncing time for the sensor in the configuration. But it's hard to test because the spike only happen sporadically.

How can I best avoid these spikes?
Higher debouncing time? Lower debouncing time?

Thank you!

![image](https://user-images.githubusercontent.com/13656866/190088030-882f1dfe-fa37-4dae-ae4a-bf542158dd89.png)

**Comment by Eisbaeeer** [comment]
Hallo
Zu diesem Projekt gibt es einen Thread. Dort wird auch auf dieses Problem eingegangen. Grundsätzlich kann man sagen, dass es an dem Sensor liegt. Der Spike entsteht nicht beim Wechsel von rot auf silber, sondern irgendwann zwischendrin. Deshalb hilft auch die Entprellung nicht. Meist hilft nur, den Sensor mit Bauteilen zu verändern, damit der die Marke sauber erkennt. 
Hier der Thread: https://forum.iobroker.net/topic/35404/ferraris-z%C3%A4hler-mit-tcrt5000-und-esp8266
Grüße Lars

**Comment by m-kloeckner** [comment]
Danke! Das mit dem Schmitt-Trigger hatte ich auch schon gelesen - führt wahrscheinlich kein Weg dran vorbei. Muss ich allerdings welche bestellen.

Alternativ werde ich mal versuchen den Analog-Ausgang zu nutzen (ich brauche nur einen Zähler am D1 Mini). Ob das besser funktioniert wird sich zeigen: https://github.com/lrswss/esp8266-wifi-power-meter

**Comment by w00dst0ck** [comment]
Du könntest Alternativ auch mal diesen Sensor probieren. Hatte damit sehr gute Ergebnisse.
https://forum.iobroker.net/topic/35404/ferraris-z%C3%A4hler-mit-tcrt5000-und-esp8266/367?_=1663145229229

Ich habe zwar mittlerweile einen Digitalen Stromzähler, aber auch da nutze ich den Sensor mit Tasmota um die Datenschnittstelle auszulesen.

Bei Übernahme des Portos, kann ich Dir auch den nicht mehr verwendeten Schmitt-Trigger zusenden.

**Comment by m-kloeckner** [comment]
Kurzes Update: Der oben verlinkte Code läuft nun seit 2 Tagen sehr stabil ohne Hardware-Modifikationen über A0. Vielleicht hilft das jemanden, der nur einen Sensor braucht und mit den digitalen Signalen des TCRT5000 Probleme hat.
